### ISSUE TITLE
vim-plug installation command is not correct

### ISSUE THREAD

**Issue by gbaranski** [mozerpol/dotfiles#1]
```bash
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
```
notice the [escape character](https://en.wikipedia.org/wiki/Escape_character), in your example, it escapes nothing. It could be either removed or followed by a new-line character, take a look at the [vim-plug repository](https://github.com/junegunn/vim-plug#unix-linux) where this snippet originally comes from
```bash
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
```

**Comment by mozerpol** [comment]
My fault when copying line from *junegunn/vim-plug* repo.
